# Generated by Django 3.2.20 on 2026-05-22 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='商品代码')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='英文名称')),
                ('category', models.CharField(choices=[('electronics', '电子产品'), ('textiles', '纺织品'), ('machinery', '机械设备'), ('chemicals', '化工产品'), ('food', '食品')], max_length=50, verbose_name='分类')),
                ('unit', models.CharField(max_length=20, verbose_name='单位')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('hs_code', models.CharField(blank=True, max_length=20, verbose_name='HS 编码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'products',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='销售价格')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='货币')),
                ('min_order', models.IntegerField(default=1, verbose_name='最小起订量')),
                ('max_order', models.IntegerField(blank=True, null=True, verbose_name='最大供应量')),
                ('lead_time', models.IntegerField(blank=True, null=True, verbose_name='交货期（天）')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可售')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='products.product')),
            ],
            options={
                'verbose_name': '商品目录',
                'verbose_name_plural': '商品目录',
                'db_table': 'catalogs',
            },
        ),
    ]
