# Generated by Django 3.2.20 on 2026-05-24 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_usercompanyrole'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='catalogs', to='roles.company'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='catalog',
            unique_together={('company', 'product')},
        ),
    ]
