# Generated by Django 3.2.20 on 2026-05-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_company_to_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSCode',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='HS编码')),
                ('name', models.CharField(max_length=500, verbose_name='商品名称')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='计量单位')),
                ('rebate_rate', models.CharField(blank=True, max_length=20, verbose_name='出口退税率')),
                ('supervision', models.CharField(blank=True, max_length=50, verbose_name='监管条件')),
                ('inspection', models.CharField(blank=True, max_length=50, verbose_name='检验检疫')),
                ('chapter', models.CharField(max_length=2, verbose_name='章节')),
                ('is_expired', models.BooleanField(default=False, verbose_name='是否过期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'HS编码',
                'verbose_name_plural': 'HS编码',
                'db_table': 'hs_codes',
                'ordering': ['code'],
            },
        ),
    ]
