# Generated by Django 3.2.20 on 2026-05-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_hscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='hscode',
            name='consumption_rate',
            field=models.CharField(blank=True, max_length=20, verbose_name='消费税率'),
        ),
        migrations.AddField(
            model_name='hscode',
            name='export_provisional',
            field=models.CharField(blank=True, max_length=20, verbose_name='出口暂定税率'),
        ),
        migrations.AddField(
            model_name='hscode',
            name='export_rate',
            field=models.CharField(blank=True, max_length=20, verbose_name='出口税率'),
        ),
        migrations.AddField(
            model_name='hscode',
            name='import_general',
            field=models.CharField(blank=True, max_length=20, verbose_name='进口普通税率'),
        ),
        migrations.AddField(
            model_name='hscode',
            name='import_provisional',
            field=models.CharField(blank=True, max_length=20, verbose_name='进口暂定税率'),
        ),
        migrations.AddField(
            model_name='hscode',
            name='mfn_rate',
            field=models.CharField(blank=True, max_length=20, verbose_name='最惠国税率'),
        ),
        migrations.AddField(
            model_name='hscode',
            name='vat_rate',
            field=models.CharField(blank=True, max_length=20, verbose_name='增值税率'),
        ),
    ]
