# Generated by Django 3.2.20 on 2026-05-23 13:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_usercompanyrole'),
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='指标标识')),
                ('display_name', models.CharField(max_length=100, verbose_name='显示名称')),
                ('dimension', models.CharField(choices=[('financial', '财务表现'), ('accuracy', '业务准确度'), ('efficiency', '操作效率'), ('negotiation', '谈判能力')], max_length=20, verbose_name='所属维度')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=5, verbose_name='默认权重')),
                ('calculation_method', models.CharField(max_length=50, verbose_name='计算方法')),
                ('config', models.JSONField(default=dict, verbose_name='计算配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('applicable_roles', models.ManyToManyField(blank=True, to='roles.TradeRole', verbose_name='适用角色')),
            ],
            options={
                'verbose_name': '评分指标',
                'verbose_name_plural': '评分指标',
                'db_table': 'scoring_metrics',
                'ordering': ['dimension', 'name'],
            },
        ),
    ]
