# Generated by Django 3.2.20 on 2026-05-23 13:07

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_usercompanyrole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scoring', '0002_scoringmetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('auto_scored', '已自动评分'), ('teacher_reviewed', '教师已审核'), ('finalized', '已定稿')], default='draft', max_length=20, verbose_name='状态')),
                ('auto_score', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='自动评分')),
                ('teacher_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='教师加减分')),
                ('final_score', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='最终分数')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='教师评语')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_sheets', to='scoring.experiment', verbose_name='实验')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sheets', to=settings.AUTH_USER_MODEL, verbose_name='审核教师')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_sheets', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
                ('user_company_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_sheets', to='roles.usercompanyrole', verbose_name='角色实例')),
            ],
            options={
                'verbose_name': '评分表',
                'verbose_name_plural': '评分表',
                'db_table': 'scoring_score_sheets',
                'ordering': ['-created_at'],
                'unique_together': {('experiment', 'user_company_role')},
            },
        ),
        migrations.CreateModel(
            name='MetricScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_value', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='原始值')),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, verbose_name='标准化得分')),
                ('details', models.JSONField(default=dict, verbose_name='计算细节')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.scoringmetric', verbose_name='评分指标')),
                ('score_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_scores', to='scoring.scoresheet', verbose_name='评分表')),
            ],
            options={
                'verbose_name': '指标得分',
                'verbose_name_plural': '指标得分',
                'db_table': 'scoring_metric_scores',
                'unique_together': {('score_sheet', 'metric')},
            },
        ),
        migrations.CreateModel(
            name='ExperimentScoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_weight', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=5, verbose_name='自定义权重')),
                ('max_adjustment', models.DecimalField(decimal_places=2, default=Decimal('20'), max_digits=5, verbose_name='加减分上限')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_configs', to='scoring.experiment', verbose_name='实验')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring.scoringmetric', verbose_name='指标')),
            ],
            options={
                'verbose_name': '实验评分配置',
                'verbose_name_plural': '实验评分配置',
                'db_table': 'scoring_experiment_configs',
                'unique_together': {('experiment', 'metric')},
            },
        ),
    ]
