# Generated by Django 3.2.20 on 2026-05-23 14:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_experimentscoringconfig_metricscore_scoresheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentscoringconfig',
            name='max_adjustment',
            field=models.DecimalField(decimal_places=2, default=Decimal('20'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='加减分上限'),
        ),
    ]
