# Generated by Django 3.2.20 on 2026-05-23 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0005_experimentgroup_experimenttemplate'),
        ('scoring', '0004_alter_experimentscoringconfig_max_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='group_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='分组配置'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='teaching_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiments', to='teaching.teachingclass', verbose_name='所属班级'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiments', to='teaching.experimenttemplate', verbose_name='来源模板'),
        ),
    ]
