# Generated by Django 3.2.20 on 2026-05-22 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2 country code', max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Country name in Chinese', max_length=100)),
                ('name_en', models.CharField(help_text='Country name in English', max_length=100)),
                ('phone_code', models.CharField(blank=True, default='', help_text='International phone dialing code', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this country is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(help_text='ISO 4217 currency code', max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Currency name in Chinese', max_length=50)),
                ('name_en', models.CharField(help_text='Currency name in English', max_length=50)),
                ('symbol', models.CharField(blank=True, default='', help_text='Currency symbol', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this currency is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'db_table': 'currencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='UN/LOCODE port code', max_length=5, unique=True)),
                ('name', models.CharField(help_text='Port name in Chinese', max_length=100)),
                ('name_en', models.CharField(help_text='Port name in English', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this port is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(help_text='Country where this port is located', on_delete=django.db.models.deletion.PROTECT, related_name='ports', to='core.country')),
            ],
            options={
                'verbose_name': 'Port',
                'verbose_name_plural': 'Ports',
                'db_table': 'ports',
                'ordering': ['name'],
            },
        ),
    ]
