# Generated by Django 3.2.20 on 2026-05-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='id',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='id',
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(help_text='ISO 3166-1 alpha-2 country code', max_length=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(help_text='ISO 4217 currency code', max_length=3, primary_key=True, serialize=False),
        ),
    ]
