# Generated by Django 3.2.20 on 2026-05-25 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100, verbose_name='国家名称')),
                ('currency_name', models.CharField(max_length=50, verbose_name='货币名称')),
                ('rate_to_usd', models.DecimalField(decimal_places=4, help_text='X 单位外币 = 1 美元', max_digits=14, verbose_name='兑美元汇率')),
                ('rate_to_cny', models.DecimalField(blank=True, decimal_places=4, help_text='1 外币 = X 人民币', max_digits=14, null=True, verbose_name='兑人民币汇率')),
                ('rate_date', models.DateField(db_index=True, verbose_name='汇率日期')),
                ('source', models.CharField(default='mofcom', max_length=50, verbose_name='数据来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='core.currency')),
            ],
            options={
                'verbose_name': '汇率',
                'verbose_name_plural': '汇率',
                'db_table': 'exchange_rates',
                'ordering': ['-rate_date'],
                'unique_together': {('currency_name', 'country_name', 'rate_date')},
            },
        ),
    ]
