# Generated by Django 3.2.20 on 2026-05-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_exchange_rate_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='country_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='代表国家'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('currency_name', 'rate_date')},
        ),
    ]
