# Generated by Django 3.2.20 on 2026-05-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dedup_exchange_rates'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomsDistrict',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='代码')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '关区',
                'verbose_name_plural': '关区',
                'db_table': 'customs_districts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CustomsDoc',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='代码')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '监管证件',
                'verbose_name_plural': '监管证件',
                'db_table': 'customs_docs',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DomesticRegion',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='代码')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '国内地区',
                'verbose_name_plural': '国内地区',
                'db_table': 'domestic_regions',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LevyMode',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='代码')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '征减免税方式',
                'verbose_name_plural': '征减免税方式',
                'db_table': 'levy_modes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='代码')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '包装种类',
                'verbose_name_plural': '包装种类',
                'db_table': 'package_types',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TradeMode',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='代码')),
                ('name', models.CharField(max_length=50, verbose_name='简称')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='全称')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '监管方式',
                'verbose_name_plural': '监管方式',
                'db_table': 'trade_modes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TransportMode',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='代码')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '运输方式',
                'verbose_name_plural': '运输方式',
                'db_table': 'transport_modes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='代码')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('conv_ratio', models.DecimalField(decimal_places=4, default=1, max_digits=10, verbose_name='换算比率')),
                ('conv_code', models.CharField(blank=True, max_length=3, verbose_name='换算目标代码')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '计量单位',
                'verbose_name_plural': '计量单位',
                'db_table': 'units_of_measure',
                'ordering': ['code'],
            },
        ),
    ]
