# Generated by Django 3.2.20 on 2026-05-21 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('commercial_invoice', '商业发票'), ('packing_list', '装箱单'), ('bill_of_exchange', '汇票'), ('sales_contract', '外销合同'), ('letter_of_credit', '信用证'), ('bill_of_lading', '海运提单'), ('insurance_policy', '保险单'), ('insurance_application', '投保单'), ('export_declaration', '出口报关单'), ('import_declaration', '进口报关单'), ('inspection_application', '报检单'), ('inspection_certificate', '检验证书'), ('certificate_of_origin', '产地证'), ('beneficiary_certificate', '受益人证明'), ('shipping_advice', '装船通知')], max_length=50, unique=True, verbose_name='单证代码')),
                ('name', models.CharField(max_length=100, verbose_name='单证名称')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='版本号')),
                ('content', models.TextField(verbose_name='模板内容 (HTML)')),
                ('is_system', models.BooleanField(default=True, verbose_name='是否系统模板')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '单证模板',
                'verbose_name_plural': '单证模板',
                'db_table': 'document_templates',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50, verbose_name='字段名')),
                ('label', models.CharField(max_length=100, verbose_name='显示标签')),
                ('field_type', models.CharField(choices=[('text', '单行文本'), ('textarea', '多行文本'), ('number', '数字'), ('decimal', '金额'), ('date', '日期'), ('select', '下拉选择'), ('country', '国家选择'), ('port', '港口选择'), ('currency', '货币选择')], max_length=20, verbose_name='字段类型')),
                ('required', models.BooleanField(default=True, verbose_name='是否必填')),
                ('default_value', models.CharField(blank=True, max_length=200, verbose_name='默认值')),
                ('validation_rules', models.TextField(blank=True, null=True, verbose_name='校验规则')),
                ('data_source', models.CharField(blank=True, max_length=100, verbose_name='数据来源')),
                ('help_text', models.CharField(blank=True, max_length=200, verbose_name='帮助文本')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='documents.documenttemplate')),
            ],
            options={
                'verbose_name': '模板字段',
                'verbose_name_plural': '模板字段',
                'db_table': 'template_fields',
                'ordering': ['sort_order', 'field_name'],
                'unique_together': {('template', 'field_name')},
            },
        ),
    ]
