# Generated by Django 3.2.20 on 2026-05-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50, verbose_name='单证类型')),
                ('depends_on', models.CharField(max_length=50, verbose_name='依赖单证类型')),
                ('dependency_type', models.CharField(choices=[('sequential', '顺序依赖'), ('parallel', '并行')], default='sequential', max_length=20, verbose_name='依赖类型')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必需')),
            ],
            options={
                'verbose_name': '单证依赖',
                'verbose_name_plural': '单证依赖',
                'db_table': 'document_dependencies',
                'unique_together': {('document_type', 'depends_on')},
            },
        ),
    ]
