# Generated by Django 3.2.20 on 2026-05-21 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0002_documentdependency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField(blank=True, null=True, verbose_name='交易ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_review', '待审核'), ('approved', '已审核'), ('rejected', '审核不通过'), ('submitted', '已提交'), ('received', '已接收'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('data', models.TextField(default=dict, verbose_name='单证数据')),
                ('auto_validation_result', models.TextField(blank=True, null=True, verbose_name='自动校验结果')),
                ('manual_review_status', models.CharField(blank=True, max_length=20, verbose_name='人工审核状态')),
                ('manual_review_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documenttemplate')),
            ],
            options={
                'verbose_name': '单证',
                'verbose_name_plural': '单证',
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
