# Generated by Django 3.2.20 on 2026-05-21 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=100, verbose_name='校验规则')),
                ('passed', models.BooleanField(verbose_name='是否通过')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('score_deduction', models.IntegerField(default=0, verbose_name='扣分')),
                ('validation_type', models.CharField(choices=[('auto', '自动校验'), ('manual', '人工审核')], max_length=10, verbose_name='校验类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='documents.document')),
            ],
            options={
                'verbose_name': '单证校验',
                'verbose_name_plural': '单证校验',
                'db_table': 'document_validations',
                'ordering': ['-created_at'],
            },
        ),
    ]
