# Generated by Django 3.2.20 on 2026-05-27 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0006_assignment_assignmentsubmission'),
        ('documents', '0004_documentvalidation'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='teaching_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='teaching.teachingclass', verbose_name='所属班级'),
        ),
    ]
