# Generated by Django 3.2.20 on 2026-05-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_teaching_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='code',
            field=models.CharField(choices=[('commercial_invoice', '商业发票'), ('packing_list', '装箱单'), ('bill_of_exchange', '汇票'), ('sales_contract', '外销合同'), ('letter_of_credit', '信用证'), ('bill_of_lading', '海运提单'), ('air_waybill', '航空运单'), ('insurance_policy', '保险单'), ('insurance_application', '投保单'), ('export_declaration', '出口报关单'), ('import_declaration', '进口报关单'), ('inspection_application', '报检单'), ('inspection_certificate', '检验证书'), ('certificate_of_origin', '产地证'), ('beneficiary_certificate', '受益人证明'), ('shipping_advice', '装船通知')], max_length=50, unique=True, verbose_name='单证代码'),
        ),
    ]
