# Generated by Django 3.2.20 on 2026-05-22 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='商品ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('inquiring', '询盘中'), ('negotiating', '还盘中'), ('pending_contract', '待签约'), ('contracted', '已签约'), ('in_progress', '履约中'), ('completed', '已完成'), ('cancelled', '已取消')], default='inquiring', max_length=20, verbose_name='状态')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='单价')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='货币')),
                ('trade_term', models.CharField(blank=True, max_length=10, verbose_name='贸易术语')),
                ('port_of_loading', models.CharField(blank=True, max_length=100, verbose_name='装运港')),
                ('port_of_discharge', models.CharField(blank=True, max_length=100, verbose_name='目的港')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buying_transactions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selling_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '交易',
                'verbose_name_plural': '交易',
                'db_table': 'transactions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='操作')),
                ('details', models.JSONField(default=dict, verbose_name='详细信息')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='transactions.transaction')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '交易日志',
                'verbose_name_plural': '交易日志',
                'db_table': 'transaction_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InquiryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(max_length=50, verbose_name='发送者角色')),
                ('message_type', models.CharField(choices=[('inquiry', '询盘'), ('offer', '发盘'), ('counter_offer', '还盘'), ('accept', '接受'), ('reject', '拒绝')], max_length=20, verbose_name='消息类型')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('offered_quantity', models.IntegerField(blank=True, null=True, verbose_name='报价数量')),
                ('offered_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='报价单价')),
                ('offered_trade_term', models.CharField(blank=True, max_length=10, verbose_name='报价贸易术语')),
                ('attachment', models.FileField(blank=True, upload_to='inquiry_attachments/', verbose_name='附件')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='transactions.transaction')),
            ],
            options={
                'verbose_name': '磋商消息',
                'verbose_name_plural': '磋商消息',
                'db_table': 'inquiry_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.CharField(max_length=50, unique=True, verbose_name='合同号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_sign', '待签字'), ('signed', '已签字'), ('effective', '已生效'), ('fulfilled', '履行完毕'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('trade_term', models.CharField(max_length=10, verbose_name='贸易术语')),
                ('payment_term', models.CharField(max_length=50, verbose_name='付款方式')),
                ('delivery_time', models.DateField(verbose_name='交货日期')),
                ('port_of_loading', models.CharField(max_length=100, verbose_name='装运港')),
                ('port_of_discharge', models.CharField(max_length=100, verbose_name='目的港')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('product_spec', models.TextField(blank=True, verbose_name='商品规格')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('unit', models.CharField(max_length=20, verbose_name='单位')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='单价')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='总金额')),
                ('currency', models.CharField(max_length=10, verbose_name='货币')),
                ('packing', models.TextField(blank=True, verbose_name='包装方式')),
                ('shipping_marks', models.TextField(blank=True, verbose_name='唛头')),
                ('remarks', models.TextField(blank=True, verbose_name='备注条款')),
                ('buyer_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='买方签字时间')),
                ('seller_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='卖方签字时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('effective_at', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='transactions.transaction')),
            ],
            options={
                'verbose_name': '外销合同',
                'verbose_name_plural': '外销合同',
                'db_table': 'contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(max_length=20, verbose_name='当事方')),
                ('signer_name', models.CharField(max_length=100, verbose_name='签字人姓名')),
                ('signature_image', models.ImageField(blank=True, upload_to='signatures/', verbose_name='签字图片')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='签字时间')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='transactions.contract')),
                ('signer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '合同签字',
                'verbose_name_plural': '合同签字',
                'db_table': 'contract_signatures',
                'unique_together': {('contract', 'party')},
            },
        ),
    ]
