# Generated by Django 3.2.20 on 2026-05-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending_confirm', '待确认'), ('pending_sign', '待签字'), ('one_signed', '一方签字'), ('signed', '已签字'), ('effective', '已生效'), ('amending', '修改中'), ('fulfilled', '履行完毕'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态'),
        ),
    ]
