# Generated by Django 3.2.20 on 2026-05-22 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterOfCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lc_no', models.CharField(max_length=50, unique=True, verbose_name='信用证号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_issue', '待开证'), ('issued', '已开证'), ('amending', '修改中'), ('submitted', '已交单'), ('negotiated', '已议付'), ('paid', '已付款'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('issuing_bank', models.CharField(max_length=200, verbose_name='开证行')),
                ('advising_bank', models.CharField(max_length=200, verbose_name='通知行')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='金额')),
                ('currency', models.CharField(max_length=10, verbose_name='货币')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='开证日期')),
                ('expiry_date', models.DateField(verbose_name='有效期')),
                ('latest_shipment_date', models.DateField(verbose_name='最迟装运日期')),
                ('port_of_loading', models.CharField(max_length=100, verbose_name='装运港')),
                ('port_of_discharge', models.CharField(max_length=100, verbose_name='目的港')),
                ('documents_required', models.JSONField(default=list, verbose_name='单据要求')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='开证时间')),
                ('advised_at', models.DateTimeField(blank=True, null=True, verbose_name='通知时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='交单时间')),
                ('negotiated_at', models.DateTimeField(blank=True, null=True, verbose_name='议付时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='付款时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_letters_of_credit', to=settings.AUTH_USER_MODEL)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiary_letters_of_credit', to=settings.AUTH_USER_MODEL)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='letter_of_credit', to='transactions.contract')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='letters_of_credit', to='transactions.transaction')),
            ],
            options={
                'verbose_name': '信用证',
                'verbose_name_plural': '信用证',
                'db_table': 'letters_of_credit',
                'ordering': ['-created_at'],
            },
        ),
    ]
