# Generated by Django 3.2.20 on 2026-05-22 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0002_letterofcredit'),
    ]

    operations = [
        migrations.CreateModel(
            name='LcAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amendment_no', models.CharField(max_length=50, verbose_name='修改编号')),
                ('content', models.JSONField(verbose_name='修改内容')),
                ('reason', models.TextField(verbose_name='修改原因')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_amendments', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('lc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='transactions.letterofcredit', verbose_name='信用证')),
            ],
            options={
                'verbose_name': '信用证修改记录',
                'verbose_name_plural': '信用证修改记录',
                'db_table': 'lc_amendments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('issue', '开证'), ('advise', '通知'), ('negotiate', '议付'), ('pay', '付款'), ('amend', '修改')], max_length=20, verbose_name='操作类型')),
                ('processed_by', models.CharField(default='system', max_length=20, verbose_name='处理方')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='处理结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_operations', to='transactions.letterofcredit', verbose_name='信用证')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_operations', to=settings.AUTH_USER_MODEL, verbose_name='操作员')),
            ],
            options={
                'verbose_name': '银行业务操作',
                'verbose_name_plural': '银行业务操作',
                'db_table': 'bank_operations',
                'ordering': ['-created_at'],
            },
        ),
    ]
