# Generated by Django 3.2.20 on 2026-05-23 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_usercompanyrole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0002_migrate_to_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(editable=False, max_length=50, unique=True, verbose_name='订单编号')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('product_code', models.CharField(blank=True, max_length=50, verbose_name='商品编码')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='数量')),
                ('unit', models.CharField(default='件', max_length=20, verbose_name='计量单位')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='单价')),
                ('currency', models.CharField(default='CNY', max_length=10, verbose_name='币种')),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=14, verbose_name='总金额')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='交货日期')),
                ('delivery_address', models.TextField(blank=True, verbose_name='交货地址')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认'), ('shipped', '已发货'), ('invoiced', '已开票'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('invoiced_at', models.DateTimeField(blank=True, null=True, verbose_name='开票时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buying_purchase_orders', to='roles.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selling_purchase_orders', to='roles.company')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='transactions.transaction')),
            ],
            options={
                'verbose_name': '采购订单',
                'verbose_name_plural': '采购订单',
                'db_table': 'purchase_orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
