# Generated by Django 3.2.20 on 2026-05-23 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roles', '0003_usercompanyrole'),
        ('transactions', '0003_purchaseorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_no', models.CharField(editable=False, max_length=50, unique=True, verbose_name='货运编号')),
                ('booking_no', models.CharField(blank=True, max_length=50, verbose_name='订舱号')),
                ('bl_no', models.CharField(blank=True, max_length=50, verbose_name='提单号')),
                ('vessel_name', models.CharField(blank=True, max_length=100, verbose_name='船名/航班号')),
                ('port_of_loading', models.CharField(max_length=100, verbose_name='装运港')),
                ('port_of_discharge', models.CharField(max_length=100, verbose_name='目的港')),
                ('etd', models.DateField(blank=True, null=True, verbose_name='预计出发日期')),
                ('eta', models.DateField(blank=True, null=True, verbose_name='预计到达日期')),
                ('container_no', models.CharField(blank=True, max_length=50, verbose_name='集装箱号')),
                ('freight_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='运费金额')),
                ('freight_currency', models.CharField(default='USD', max_length=10, verbose_name='运费币种')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('booked', '已订舱'), ('loaded', '已装船'), ('shipped', '已签发提单'), ('arrived', '已到港'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('booked_at', models.DateTimeField(blank=True, null=True, verbose_name='订舱时间')),
                ('loaded_at', models.DateTimeField(blank=True, null=True, verbose_name='装船时间')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='签发提单时间')),
                ('arrived_at', models.DateTimeField(blank=True, null=True, verbose_name='到港时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_shipments', to='roles.company')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='transactions.contract')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipments', to=settings.AUTH_USER_MODEL)),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_shipments', to='roles.company')),
            ],
            options={
                'verbose_name': '货运订单',
                'verbose_name_plural': '货运订单',
                'db_table': 'shipments',
                'ordering': ['-created_at'],
            },
        ),
    ]
