# Generated by Django 3.2.20 on 2026-05-23 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roles', '0003_usercompanyrole'),
        ('transactions', '0004_shipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_no', models.CharField(editable=False, max_length=50, unique=True, verbose_name='保单号')),
                ('cargo_description', models.TextField(verbose_name='货物描述')),
                ('insured_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='投保金额')),
                ('premium', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='保费')),
                ('premium_currency', models.CharField(default='CNY', max_length=10, verbose_name='保费币种')),
                ('coverage_type', models.CharField(choices=[('fpa', '平安险'), ('wa', '水渍险'), ('all_risk', '一切险')], default='all_risk', max_length=20, verbose_name='险种')),
                ('status', models.CharField(choices=[('applied', '已投保'), ('underwritten', '已承保'), ('issued', '已签发'), ('cancelled', '已取消')], default='applied', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('underwritten_at', models.DateTimeField(blank=True, null=True, verbose_name='承保时间')),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='签发时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policy', to='transactions.contract')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_insurance_policies', to=settings.AUTH_USER_MODEL)),
                ('insured', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insured_policies', to='roles.company')),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_policies', to='roles.company')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_policies', to='transactions.shipment')),
            ],
            options={
                'verbose_name': '保险单',
                'verbose_name_plural': '保险单',
                'db_table': 'insurance_policies',
                'ordering': ['-created_at'],
            },
        ),
    ]
