# Generated by Django 3.2.20 on 2026-05-23 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roles', '0003_usercompanyrole'),
        ('transactions', '0005_insurancepolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomsDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_no', models.CharField(editable=False, max_length=50, unique=True, verbose_name='报关单号')),
                ('hs_code', models.CharField(max_length=20, verbose_name='HS编码')),
                ('goods_name', models.CharField(max_length=200, verbose_name='品名')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='数量')),
                ('unit_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='单价')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='总价')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='币种')),
                ('duty_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='关税率')),
                ('duty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='关税金额')),
                ('vat_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='增值税率')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='增值税金额')),
                ('status', models.CharField(choices=[('declared', '已申报'), ('reviewing', '审核中'), ('assessed', '已征税'), ('cleared', '已放行'), ('rejected', '已退单')], default='declared', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('assessed_at', models.DateTimeField(blank=True, null=True, verbose_name='征税时间')),
                ('cleared_at', models.DateTimeField(blank=True, null=True, verbose_name='放行时间')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='退单时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_declarations', to=settings.AUTH_USER_MODEL)),
                ('customs_office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_declarations', to='roles.company')),
                ('declarant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customs_declarations', to='roles.company')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customs_declarations', to='transactions.shipment')),
            ],
            options={
                'verbose_name': '出口报关单',
                'verbose_name_plural': '出口报关单',
                'db_table': 'customs_declarations',
                'ordering': ['-created_at'],
            },
        ),
    ]
