# Generated by Django 3.2.20 on 2026-05-23 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_usercompanyrole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0006_customsdeclaration'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.CharField(editable=False, max_length=50, unique=True, verbose_name='报检号')),
                ('product_name', models.CharField(max_length=200, verbose_name='品名')),
                ('product_spec', models.CharField(blank=True, max_length=200, verbose_name='规格')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='数量')),
                ('goods_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='货值')),
                ('inspection_type', models.CharField(choices=[('legal', '法定检验'), ('general', '一般鉴定')], default='legal', max_length=20, verbose_name='检验类型')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='检验费')),
                ('fee_currency', models.CharField(default='CNY', max_length=10, verbose_name='费用币种')),
                ('certificate_no', models.CharField(blank=True, max_length=50, verbose_name='检验证书号')),
                ('origin_certificate_no', models.CharField(blank=True, max_length=50, verbose_name='产地证号')),
                ('status', models.CharField(choices=[('applied', '已报检'), ('inspecting', '检验中'), ('passed', '合格'), ('certified', '已签发证书'), ('failed', '不合格')], default='applied', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('inspecting_at', models.DateTimeField(blank=True, null=True, verbose_name='开始检验时间')),
                ('passed_at', models.DateTimeField(blank=True, null=True, verbose_name='合格时间')),
                ('certified_at', models.DateTimeField(blank=True, null=True, verbose_name='签发时间')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='不合格时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_applications', to='roles.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inspections', to=settings.AUTH_USER_MODEL)),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_inspections', to='roles.company')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_applications', to='transactions.shipment')),
            ],
            options={
                'verbose_name': '检验申请',
                'verbose_name_plural': '检验申请',
                'db_table': 'inspection_applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
