# Generated by Django 3.2.20 on 2026-05-23 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_usercompanyrole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0007_inspectionapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForexSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_no', models.CharField(editable=False, max_length=50, unique=True, verbose_name='结算单号')),
                ('foreign_currency', models.CharField(default='USD', max_length=10, verbose_name='外币币种')),
                ('foreign_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='外币金额')),
                ('reference_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='参考汇率')),
                ('reference_cny_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='参考人民币金额')),
                ('settlement_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='结汇汇率')),
                ('settlement_cny_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='结汇人民币金额')),
                ('status', models.CharField(choices=[('applied', '已申请'), ('verified', '已核销'), ('settled', '已结汇'), ('rejected', '已拒绝')], default='applied', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='核销时间')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='结汇时间')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='拒绝时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forex_settlements', to='roles.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forex_settlements', to=settings.AUTH_USER_MODEL)),
                ('customs_declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forex_settlements', to='transactions.customsdeclaration')),
                ('forex_bureau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_forex_settlements', to='roles.company')),
            ],
            options={
                'verbose_name': '外汇结算',
                'verbose_name_plural': '外汇结算',
                'db_table': 'forex_settlements',
                'ordering': ['-created_at'],
            },
        ),
    ]
