# Generated by Django 3.2.20 on 2026-05-23 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roles', '0003_usercompanyrole'),
        ('transactions', '0008_forexsettlement'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRefundApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.CharField(editable=False, max_length=50, unique=True, verbose_name='退税申请号')),
                ('hs_code', models.CharField(max_length=20, verbose_name='HS编码')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='报关总价值')),
                ('refund_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5, verbose_name='退税率')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='退税金额')),
                ('refund_currency', models.CharField(default='CNY', max_length=10, verbose_name='退税币种')),
                ('status', models.CharField(choices=[('applied', '已申请'), ('reviewing', '审核中'), ('approved', '已批准'), ('refunded', '已退税'), ('rejected', '已拒绝')], default='applied', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('reviewing_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='批准时间')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='退税时间')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='拒绝时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_refund_applications', to='roles.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tax_refunds', to=settings.AUTH_USER_MODEL)),
                ('customs_declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_refund_applications', to='transactions.customsdeclaration')),
                ('tax_bureau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_tax_refunds', to='roles.company')),
            ],
            options={
                'verbose_name': '出口退税申请',
                'verbose_name_plural': '出口退税申请',
                'db_table': 'tax_refund_applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
