# Generated by Django 3.2.20 on 2026-05-24 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_company_to_catalog'),
        ('transactions', '0010_remove_transaction_null_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='product_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='products.product'),
        ),
    ]
