# Generated by Django 3.2.20 on 2026-06-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_product_fk_non_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquirymessage',
            name='offered_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='报价交货日期'),
        ),
        migrations.AddField(
            model_name='inquirymessage',
            name='offered_insurance',
            field=models.CharField(blank=True, max_length=200, verbose_name='报价保险条款'),
        ),
        migrations.AddField(
            model_name='inquirymessage',
            name='offered_packing',
            field=models.TextField(blank=True, verbose_name='报价包装要求'),
        ),
        migrations.AddField(
            model_name='inquirymessage',
            name='offered_payment_term',
            field=models.CharField(blank=True, choices=[('lc', '信用证 (L/C)'), ('dp', '付款交单 (D/P)'), ('da', '承兑交单 (D/A)'), ('tt', '电汇 (T/T)'), ('tt_advance', '前T/T (预付)'), ('tt_sight', '后T/T (货到付款)'), ('wu', '西联汇款'), ('other', '其他')], max_length=20, verbose_name='报价付款方式'),
        ),
        migrations.AddField(
            model_name='inquirymessage',
            name='offered_product_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='报价商品编码'),
        ),
        migrations.AddField(
            model_name='inquirymessage',
            name='offered_product_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='报价商品名称'),
        ),
        migrations.AddField(
            model_name='inquirymessage',
            name='offered_quality_standard',
            field=models.TextField(blank=True, verbose_name='报价质量标准'),
        ),
    ]
