# Generated by Django 3.2.20 on 2026-06-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_auto_20260602_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='交货日期'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='insurance',
            field=models.CharField(blank=True, max_length=200, verbose_name='保险条款'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='packing',
            field=models.TextField(blank=True, verbose_name='包装要求'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_term',
            field=models.CharField(blank=True, choices=[('lc', '信用证 (L/C)'), ('dp', '付款交单 (D/P)'), ('da', '承兑交单 (D/A)'), ('tt', '电汇 (T/T)'), ('tt_advance', '前T/T (预付)'), ('tt_sight', '后T/T (货到付款)'), ('wu', '西联汇款'), ('other', '其他')], max_length=20, verbose_name='付款方式'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='商品名称'),
        ),
    ]
