# Generated by Django 3.2.20 on 2026-06-02 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='documents_per_page',
            field=models.PositiveIntegerField(default=5, help_text='单证列表每页显示数量', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
