# Generated by Django 3.2.20 on 2026-05-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('exporter', '出口商'), ('importer', '进口商'), ('factory', '工厂'), ('bank', '银行'), ('customs', '海关'), ('shipping', '货运公司'), ('insurance', '保险公司'), ('inspection', '商检机构'), ('forex', '外汇局'), ('tax', '税务局')], max_length=50, unique=True, verbose_name='角色代码')),
                ('name', models.CharField(max_length=100, verbose_name='角色名称')),
                ('description', models.TextField(verbose_name='职责说明')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_system', models.BooleanField(default=True, verbose_name='系统预置')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '贸易角色',
                'verbose_name_plural': '贸易角色',
                'db_table': 'trade_roles',
                'ordering': ['sort_order', 'code'],
            },
        ),
    ]
