# Generated by Django 3.2.20 on 2026-05-22 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roles', '0002_traderole'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompanyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已拒绝'), ('active', '激活中'), ('suspended', '已暂停')], default='pending', max_length=20, verbose_name='状态')),
                ('is_active', models.BooleanField(default=False, verbose_name='当前激活')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='批准时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_role_assignments', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='roles.company')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='roles.traderole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户角色分配',
                'verbose_name_plural': '用户角色分配',
                'db_table': 'user_company_roles',
                'ordering': ['-requested_at'],
                'unique_together': {('user', 'company', 'role')},
            },
        ),
    ]
