# Generated by Django 3.2.20 on 2026-05-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_usercompanyrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, verbose_name='公司简介'),
        ),
    ]
