# Generated by Django 3.2.20 on 2026-05-23 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='学期名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='学期代码')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('is_active', models.BooleanField(default=False, verbose_name='当前学期')),
                ('status', models.CharField(choices=[('upcoming', '未开始'), ('active', '进行中'), ('ended', '已结束')], default='upcoming', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_semesters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学期',
                'verbose_name_plural': '学期',
                'db_table': 'semesters',
                'ordering': ['-start_date'],
            },
        ),
    ]
