# Generated by Django 3.2.20 on 2026-05-23 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teaching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='课程名称')),
                ('code', models.CharField(max_length=20, verbose_name='课程代码')),
                ('description', models.TextField(blank=True, verbose_name='课程简介')),
                ('experiment_weight', models.DecimalField(decimal_places=2, default=0.6, max_digits=5, verbose_name='实验成绩权重')),
                ('assignment_weight', models.DecimalField(decimal_places=2, default=0.4, max_digits=5, verbose_name='作业成绩权重')),
                ('status', models.CharField(choices=[('upcoming', '未开始'), ('active', '进行中'), ('ended', '已结束')], default='upcoming', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='teaching.semester')),
                ('teachers', models.ManyToManyField(blank=True, related_name='teaching_courses', to=settings.AUTH_USER_MODEL, verbose_name='授课教师')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'courses',
                'ordering': ['-created_at'],
                'unique_together': {('semester', 'code')},
            },
        ),
    ]
