# Generated by Django 3.2.20 on 2026-05-23 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teaching', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='班级名称')),
                ('capacity', models.IntegerField(default=40, verbose_name='最大人数')),
                ('enrollment_code', models.CharField(max_length=20, unique=True, verbose_name='选课码')),
                ('status', models.CharField(choices=[('upcoming', '未开始'), ('active', '进行中'), ('ended', '已结束')], default='upcoming', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='teaching.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '教学班级',
                'verbose_name_plural': '教学班级',
                'db_table': 'teaching_classes',
                'ordering': ['-created_at'],
            },
        ),
    ]
