# Generated by Django 3.2.20 on 2026-05-23 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teaching', '0003_teachingclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', '学生'), ('assistant', '助教'), ('monitor', '班长')], default='student', max_length=20, verbose_name='角色')),
                ('status', models.CharField(choices=[('enrolled', '已选课'), ('dropped', '已退课')], default='enrolled', max_length=20, verbose_name='状态')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='选课时间')),
                ('dropped_at', models.DateTimeField(blank=True, null=True, verbose_name='退课时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('teaching_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='teaching.teachingclass')),
            ],
            options={
                'verbose_name': '学生选课',
                'verbose_name_plural': '学生选课',
                'db_table': 'student_enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('teaching_class', 'student')},
            },
        ),
    ]
