# Generated by Django 3.2.20 on 2026-05-23 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_usercompanyrole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scoring', '0004_alter_experimentscoringconfig_max_adjustment'),
        ('teaching', '0004_studentenrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('config', models.JSONField(default=dict, verbose_name='预设配置')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('use_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_experiment_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '实验模板',
                'verbose_name_plural': '实验模板',
                'db_table': 'experiment_templates',
                'ordering': ['-use_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, verbose_name='组名')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_group', to='roles.company')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='scoring.experiment')),
            ],
            options={
                'verbose_name': '实验分组',
                'verbose_name_plural': '实验分组',
                'db_table': 'experiment_groups',
                'ordering': ['group_name'],
            },
        ),
    ]
