# Generated by Django 3.2.20 on 2026-05-31 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teaching', '0006_assignment_assignmentsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True, verbose_name='学号')),
                ('admin_class', models.CharField(blank=True, max_length=100, verbose_name='行政班级')),
                ('grade', models.CharField(blank=True, max_length=20, verbose_name='年级')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('enrollment_year', models.IntegerField(blank=True, null=True, verbose_name='入学年份')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '学生档案',
                'verbose_name_plural': '学生档案',
                'db_table': 'student_profiles',
            },
        ),
    ]
