# Generated by Django 3.2.20 on 2026-05-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaching', '0007_studentprofile'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='teachingclass',
            index=models.Index(fields=['course', '-created_at'], name='teaching_cl_course__f7ace9_idx'),
        ),
        migrations.AddIndex(
            model_name='teachingclass',
            index=models.Index(fields=['created_by'], name='teaching_cl_created_98416b_idx'),
        ),
        migrations.AddIndex(
            model_name='teachingclass',
            index=models.Index(fields=['status'], name='teaching_cl_status_55a02b_idx'),
        ),
    ]
